baseurl = "http://peterjordan.info/"
languageCode = "en-us"
title = "Peter Jordan"
theme = "hugo-steam-theme"
disqusShortname = "peterjordaninfo"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = "UA-58438469-1"
# Number of posts per page
paginate = 10

[params]
	title = "Peter Jordan"
	subtitle = "DIGITAL STRATEGY: THOUGHTS, STORIES AND IDEAS"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Peter Jordan"
	bio = "Peter is a digital strategist with a focus on digital analytics, performance analysis and findability"
	description = "Your description of the blog"
	
	# Link your social networks (optional)
	location = ""
	twitter = "peterbjordan"
	# linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "spf13"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
